### ISSUE TITLE
Is it possible to have ReformatOnSave:True for VS plugin saved to source control?

### ISSUE THREAD

**Issue by DaveNay** [belav/csharpier#1045]
Currently, it appears that the VS plugin saves the ReformatOnSave to the csharpier.json file in the .vs directory. Since this directory is typically excluded from source control, this means that all users must enable ReformatOnSave in their local environment. Additionally, if the .vs directory is deleted (e.g. running git clean on the repo) then the ReformatOnSave setting is lost.

Ideally, I think it would be nice if this setting were part of the .csharpierrc file and could be tracked by source control, thus enabling ReformatOnSave for all users reliably. I have not explored the VS Code plugin, but it should behave in the same manner as I describe.

**Comment by DaveNay** [comment]
> Moving the setting into .csharpierrc would force it on all users.

Exactly :smile:

What if the settings in `.csharpierrc` and `csharpier.json` were hierarchical? If the `ReformatOnSave` setting is missing or null in `.csharpierrc`, then the value from `csharpier.json` is applied. If the setting is not null in `.csharpierrc`, then it takes precedence. This would also preserve backwards compatibility for everyone that is using the setting from `csharpier.json`.

The trickiest part would be having the VS UI reflect the correct value depending on what is defined and what isn't.

**Comment by sea1jxr** [comment]
We have them same need, our developers are jumping between repos with different formatting solutions, so a solution that allows format on save to be turned on at a repo/directory level is ideal.

@belav would you be ok with the solution @DaveNay suggested where a default value can be pulled from the .csharpierrc/.editorconfig and can be overridden using the global and/or solution VS settings?

I am keen to create a PR for this, but it would mean that the config loading code would need to be shared between cli and visualstudio extension.  Also since VSCode already has a great way to do this with workspaces as you mentioned, the options would likely be named something like VsFormatOnSaveDefault.

**Comment by belav** [comment]
I don't think it makes sense to add a VS specific setting to the CSharpier configuration files. It adds confusion to the documentation and the UI for the current settings in VS.

As I mentioned above, you can add `.vs/[Project]/v17/csharpier.json` if you want all team members to have format on save turned on.

The only thing I'd like to do is find a solution that allows the rider setting to be defined system wide.
