### ISSUE TITLE
"Reformat with CSharpier" option disappeared

### ISSUE THREAD

**Issue by wojsza05** [belav/csharpier#1056]
I have been using the CSharpier extension in Visual Studio for a long time. After some update in recent days, the "Reformat with CSharpier" option disappeared from the options available by right-clicking. The keyboard shortcut I had set to formatting also stopped working. Uninstalling the extension and installing it again didn't help. Does anyone know how to solve this problem?

**Comment by belav** [comment]
The troubleshooting steps [here](https://csharpier.com/docs/EditorsTroubleshooting) should help track down the issue. The problem is probably with being unable to install/run csharpier. And if you updated to 0.26.x, it could be that you don't have net8 installed. It seems that the way the extension makes use of csharpier, it requires net8, even though csharpier targets 6, 7 and 8.

Going back to 0.25.0 is a possible easy workaround.

I will also have the VS extension updated shortly to provide more helpful messaging when it runs into a problem with installing/running csharpier.

**Comment by wojsza05** [comment]
Thank you for your help, your advice guided me to the right action and it's working again.
However, it's hard for me to say what happened, I uninstalled CSharpier (not the Visual Code extension), then installed the same version again and it started working.
