### ISSUE TITLE
Add automatic removal of interface member access modifiers

### ISSUE THREAD

**Issue by portyanikhin** [belav/csharpier#1081]
Hello!

Thank you for your valuable work!

I want to suggest a new feature for a future release.
I think it would be great if CSharpier would automatically remove access modifiers for interface members, because they are completely unnecessary there.

**Input:**

```csharp
public interface IFoo
{
    public int Bar { get; }
    public void Baz();
}
```

**Output:**

```csharp
public interface IFoo
{
    public int Bar { get; }
    public void Baz();
}
```

**Expected output:**

```csharp
public interface IFoo
{
    int Bar { get; }
    void Baz();
}
```

**Comment by ShawnTheBeachy** [comment]
How far would removing pointless access modifiers go? Should 

```c#
internal class Fruit
{
    internal string Name { get; set; }
}
```

be changed to

```c#
internal class Fruit
{
    public string Name { get; set; }
}
```
?
Or should it be left as is since changing the class access modifier would affect property access?

**Comment by belav** [comment]
I'm a little hesitant to add this because it feels a bit outside the scope of CSharpier. The only two exceptions to the "only change whitespace" guideline were a pain to deal with due to figuring out how to get the syntax tree validation to not flag them as problems with code being lost.

Other modifiers are also unnecessary but it is pretty standard to always include them. Should CSharpier then enforce adding the following modifiers -

If no modifier is on an interface should CSharpier change it to `public interface`? 
Should classes without modifiers be changed to `internal class`? 
Should members of classes without modifiers have `private` added?

**Comment by ShawnTheBeachy** [comment]
If the idea is to not change behavior, then your first example should probably be changed instead to `internal interface`.

But, on further thought, I'm removing my vote. IMO the behavior would be less than obvious. For example, it would not make sense to change this

```c#
internal sealed class MaybeThisShouldBePublic
{
    internal string MyInternalOnlyProperty { get; set; }
}
```

to this

```c#
internal sealed class MaybeThisShouldBePublic
{
    public string MyInternalOnlyProperty { get; set; }
}
```
because even though the `internal` modifier on the property is currently useless, if CSharpier were to change the property accessor to `public` and then the user later changed the class to `public`, CSharpier may have just exposed a property that shouldn't have been exposed. So a case like that would need to be left alone. But to me as a user it wouldn't be obvious why CSharpier _sometimes_ removes/adds/changes modifiers -- but not always.

**Comment by portyanikhin** [comment]
Having read your arguments, I probably agree that this issue is a bit beyond the scope of CSharpier's responsibility, because it can potentially change the behavior of the source code. Yes, there are many special cases here. I think it's better for the developer to make his own decision about the access modifier, depending on the situation.

Thanks for the feedback!
Closing the issue.
