### ISSUE TITLE
Support HTTP

### ISSUE THREAD

**Issue by belav** [belav/csharpier#1109]
0.27.2 is adding http support so that the extensions don't need to depend on sending data back and forth via stdin/stdout.

This issue is to get the extensions updated with opt-in support for it.

Rider and VS are started.
VSCode is not.

There needs to be a timeout when calling the server, this doesn't exist in any of them yet.
There needs to be some way to get logs, or have csharpier log what it is doing. To help troubleshoot issues.

**Comment by blahDL** [comment]
Have you considered using [SignalR](https://learn.microsoft.com/en-us/aspnet/signalr/) or similar to enable you to send messages from the server back to the client?

A SignalR hub like this could work for sending format requests to the server and log messages back to the client:
```csharp
[Route("communication")]
public class CommunicationHub : Hub<ICommunicationHub>
{
	private readonly CSharpierServiceImplementation _service;

	public CommunicationHub(CSharpierServiceImplementation service)
	{
		_service = service;
	}

	public async Task<FormatFileResult> Format(FormatFileParameter formatFileDto, CancellationToken cancellationToken)
	{
		return await _service.FormatFile(formatFileDto, cancellationToken);
	}
}

public interface ICommunicationHub
{
	Task Log(string message);
}
```

Then you can create a logger that takes the hub (`IHubContext<CommunicationHub, ICommunicationHub>`) as a parameter in the constructor then writes the log messages to the client via `await hub.Clients.All.Log("the log message")`

This would also require changing the clients to connect to the SignalR hub instead of just sending POST requests, but it will allow you to send data in both directions
