### ISSUE TITLE
Rider's "Run on Save" doesn't detect an auto-save from builds, etc

### ISSUE THREAD

**Issue by phillijw** [belav/csharpier#1212]
**Environments**
- IDE Version: Rider 2023.3.3
- Extension Version: 1.6.1
- CSharpier Version:  0.25.0
- Operating System: macOS
- .csharpierrc Settings: `{ "printWidth": 200 }`
- .editorconfig Settings:

**Log Output**

**Steps to reproduce**
1. Make a formatting change to a file
2. Build the solution or project without saving first

**Expected behavior**
csharpier should run on any auto-saved files

**Actual behavior**
csharpier doesn't recognize that a file was saved

**Comment by belav** [comment]
This has caused me some grief when doing renaming/find replacing across files and I never thought to dig into it more. Turns out it was straightforward to respond to all reasons for a document being saved. Thanks for reporting it!

Will be fixed with 1.6.4 when jetbrains approves it, usually takes a day or two.
