### ISSUE TITLE
Add an option to write the formatted file to stdout

### ISSUE THREAD

**Issue by saborrie** [belav/csharpier#282]
It would be great to be able to create a vscode extension for this formatter that is compatible with vscode's format-on-save.

It would be best if it were possible to leave the actual editing of the file contents to vscode, and to just print out the new file contents to stdout.

This doesn't need to be for multiple files in this use case.

This is how prettier works (except when using `--write`), so it makes sense to work in the same way.

Additionally it would help to support accepting a file from stdin rather than a path, so that it  can be made to work with virtual filesystems.

**Comment by belav** [comment]
> It would be great to be able to create a vscode extension for this formatter that is compatible with vscode's format-on-save.  

Definitely! It's been on my list forever now to start to figure out IDE integration, but hasn't been a priority yet.

I don't think it will be too difficult to write to stdout. It will probably not be the default because that would be a breaking change. 
My initial thought is adding an option such as `--write-stdout`

I'll look at accepting a file from stdin at the same time, but may split that off into another issue if it isn't super straightforward.
