### ISSUE TITLE
VSCode Extension

### ISSUE THREAD

**Issue by belav** [belav/csharpier#283]
It would be great to have an extension similar to https://github.com/prettier/prettier-vscode 

This is mainly just a placeholder for getting the work started and determining what needs to be done.

Format on save will require #282

**Comment by shocklateboy92** [comment]
I was thinking we could do one better, and integrate it directly into omnisharp. That way, all the 'format' actions would use csharpier by default and have a smoother experience than just formatting on save.

However, as per OmniSharp/omnisharp-roslyn#2167, they don't think omnisharp is the place for it. I want to try adding that functionality directly into Rosyln itself. So that way, people can specify the formatter (and version) as a nuget package, much like how [Roslynator](https://github.com/JosefPihrt/Roslynator) provides refactorings and code analysis.

**Comment by belav** [comment]
Interesting... if roslyn allows formatters, that would remove the need for a lot of the IDE integration work.

If we do start down the VSCode extension path, I ran across this link which would be useful - https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices

**Comment by shocklateboy92** [comment]
Okay, I chatted with @sharwell offline and he's of the opinion that unless a formatter handles all possible scenarios (including incomplete code that doesn't compile), it shouldn't go to Roslyn. While I don't fully agree, I respect his position. This means the roslyn path is a no-go.

I'll probably create a vim extension before VS-code one (because I use the former more than the latter), but we will need some changes in csharpier cli to make it work.

## Keeping it running between formats
Currently, (especially for small files) it seems the dotnet process spends more time initializing than the actual meat of parsing/formatting. In order avoid the perf hit when running on save, we should keep csharpier running as long as the editor is.

We could do something complicated like make csharpier serve an http endpoint that takes the code and formats it, but I'm hoping we can get away with something simple and continue to use stdin. If we can make csharpier/dotnet not close the buffer on the `EOF` byte, we can use that to delimit multiple files/runs. 

## Keeping version in project
One of the reasons I wanted to push for a nuget/roslyn based approach like Roslynator is that then the formatter and version will be specified in the csproject as a nuget reference. That way, all team members who contribute to a specific project will format the same (despite has changing formatting rules between versions).

This doesn't really need changes in csharpier cli I suppose, but I'm mentioning it here for completeness. The way @sharwell suggested it was to use dotnet tool manifest. Essentially, don't ship a version of csharpier with the vs-code/vim plugin, but have it invoke it as a dotnet tool. That way, if a manifest specifies the version, it will use that, otherwise it will fall back to the user's global version.

**Comment by belav** [comment]
> including incomplete code that doesn't compile

Right now csharpier spits back out the exact code it got when it fails to compile, I'm not sure if that would qualify as handling it.

> Currently, (especially for small files) it seems the dotnet process spends more time initializing than the actual meat of parsing/formatting.

That was definitely the case when csharpier was still a prettier plugin. It started a new .net process for each file, which completely killed performance. I decided to port it to .net instead of trying to figure out how to keep the process alive. Serializing the AST to json was also taking a pretty big chunk of time and there didn't seem to be a good solution to that problem.

**Comment by saborrie** [comment]
I just saw #282 is done and you'd added support for stdin/stdout so I've had a go at a proof-of-concept vscode extension using that: https://github.com/saborrie/vscode-csharpier

it has this nodejs function: 

```ts
import * as cp from "child_process";

function runFormatter(input: string): Promise<string> {
  return new Promise((resolve, reject) => {

    const csharpier = cp.spawn("dotnet", ["csharpier", "--write-stdout"], {
      stdio: "pipe",
    });

    let output = "";
    csharpier.stdout.on("data", (chunk) => {
      output += chunk.toString();
    });
    csharpier.on("exit", () => {
      resolve(output);
    });

    csharpier.stdin.write(input);
    csharpier.stdin.end();
  });
}
```

Hope this helps in some way. I'll post another comment here tomorrow (or soon) with some ideas I've had.

**Comment by belav** [comment]
Awesome! I don't know anything about writing vscode extensions (yet) so this will definitely help. 

I'd like to focus on improving the formatting of csharpier, but once it gets to something we can call beta then take on things like the VSCode extension. 

But if you or anyone else wants to work on the extension sooner just let me know if there is anything I can do to help

**Comment by saborrie** [comment]
I've been busy but I've tried to throw together some notes and a diagram:

 Would it be best to move any vscode extension (plus any other extra packages) into the main Csharpier repo?
  A monorepo might be easier to manage as new versions of Csharpier can be verioned and then released along with updates to all extensions.
  Alternatively, does it make sense to create a csharpier github organisation to put all the csharpier related repos into (like https://github.com/prettier/prettier-vscode)?

Vscode is nodejs based, in my proof-of-concept extension I wrote a function in node which can call csharpier by spawning another process. I think it would make sense to set this up as a standalone `node-csharpier` package, which can then be imported into the vscode extension.

As shocklateboy92 wrote, it would be good to have a way to fix the Csharpier version used within a project - especially if the formatting of csharpier continues to be worked on. This means that there will need to be a way of installing a local version of csharpier on a per project basis. However you do this (perhaps with a `node-csharpier` install) then the vscode extension could look for a local version, and if not found fall back to the global version.


A possible structure:

![image](https://user-images.githubusercontent.com/4096734/126321302-0c17b8df-bdcc-4f82-83a1-eb5d1c9c15a8.png)

**Comment by shocklateboy92** [comment]
Thanks for your work (and diagrams) @saborrie! Much appreciated :heart: 

> Would it be best to move any vscode extension (plus any other extra packages) into the main Csharpier repo?

Yes. Create a `CSharpier.VsCode` directory under `Src/` of this repo.

> Alternatively, does it make sense to create a csharpier github organisation to put all the csharpier related repos into

We will most likely do so in the future, but I don't think we need to just yet.

> Vscode is nodejs based, in my proof-of-concept extension I wrote a function in node which can call csharpier by spawning another process.

How did you find the performance in your POC? Did it make saving things in VS Code feel "sluggish"?

> I think it would make sense to set this up as a standalone node-csharpier package, which can then be imported into the vscode extension

Any particular reason? Do you envision many other projects needing to invoke csharpier in Js/Ts?

>This means that there will need to be a way of installing a local version of csharpier on a per project basis. However you do this (perhaps with a node-csharpier install) then the vscode extension could look for a local version, and if not found fall back to the global version.

So, dotnet tools already support a per-workspace manifest/versioning like npm/yarn's `package.json`:
https://docs.microsoft.com/en-us/dotnet/core/tools/local-tools-how-to-use
I'm pretty sure when you spawn `dotnet csharpier` from `child_process`, it will already try the local version and then fall back to global. 

You should add some helpful messaging in the UI explaining this to users and maybe some functionality to install a local/global version easily. Not sure what this would look like.

**Comment by saborrie** [comment]
> > Vscode is nodejs based, in my proof-of-concept extension I wrote a function in node which can call csharpier by spawning another process.
> 
> How did you find the performance in your POC? Did it make saving things in VS Code feel "sluggish"?

It was slightly sluggish - I even tried spawning the process before the formatting function call and then only piping stdin but it made no difference. I think it does need to be done with a single long running process rather than stopping and starting csharpier, but I'm not sure how. I might have suggested gRPC if not for seeing this: https://gist.github.com/badsyntax/9827722afcb33a4b0e03c809f1aede98. Perhaps it's possible to use protobuf over stdin/stdout which would have the advantage over just sending the formatted text as it can support metadata like time taken, errors etc.
 
> > I think it would make sense to set this up as a standalone node-csharpier package, which can then be imported into the vscode extension
> 
> Any particular reason? Do you envision many other projects needing to invoke csharpier in Js/Ts?

1. I was thinking this would make development of the node->csharpier communication easier. Even if you don't publish it to the npm registry, by separating it you can write a separate test suite for it and it can be worked on in isolation. 

2. I'd mostly expect to see it in automation pipeline scenarios. It would be useful to have an easy way to invoke csharpier from nodejs for anyone using tools like [gulp](https://gulpjs.com/), or even just regular nodejs scripts.

> > This means that there will need to be a way of installing a local version of csharpier on a per project basis. However you do this (perhaps with a node-csharpier install) then the vscode extension could look for a local version, and if not found fall back to the global version.
> 
> So, dotnet tools already support a per-workspace manifest/versioning like npm/yarn's `package.json`:
> https://docs.microsoft.com/en-us/dotnet/core/tools/local-tools-how-to-use
> I'm pretty sure when you spawn `dotnet csharpier` from `child_process`, it will already try the local version and then fall back to global.
> 
> You should add some helpful messaging in the UI explaining this to users and maybe some functionality to install a local/global version easily. Not sure what this would look like.

I'll give that a try in the POC and see what it takes to detect whether it's installed in the local folder. I did think of a problem which is that the vscode editor might not actually be open in the same directory as any manifest files, and when particular files get formatted, they might be within a subdirectory that had a different manifest file than the root, plus vscode supports formatting unsaved/untitled files.

**Comment by belav** [comment]
As someone who knows almost nothing about writing console apps or stdin/stdout beyond what I learned working on csharpier and knows nothing about protobuf or gRPC....

I played around with trying to get a POC of a long running console app that could read multiple files from stdin. The potential solution I came up with was sending a specific set of characters to the app to indicate the end of a file. When the app sees those characters it formats what it already read, and then waits for more data on stdin.

It feels hacky, would need to key off of something that is guaranteed to not exist in a real file, couldn't really read line by line because csharpier needs to see the line endings, and I have no idea what reading character by character may do to performance.

There really should be a better way to do this, but trying to google it didn't get me anywhere.

The POC
```js
  const longRunner = spawn("LongRunner.exe", [], {
      stdio: "pipe"
  });

  longRunner.stdout.on("data", chunk => {
      console.log(chunk.toString());
  });

  longRunner.stdin.write("test1\n")
  longRunner.stdin.write("blah blah\n")
  longRunner.stdin.write("ENDOFFILE\n")
  await sleep(100);

  longRunner.stdin.write("test2\n")
  longRunner.stdin.write("ENDOFFILE\n")
  await sleep(100);
```
```c#
using var streamReader = new StreamReader(
    Console.OpenStandardInput(),
    Console.InputEncoding
);
var stringBuilder = new StringBuilder();
var line = await streamReader.ReadLineAsync();
while (line != null)
{
    if (line == "ENDOFFILE")
    {
        Console.WriteLine("file: ");
        Console.WriteLine(stringBuilder.ToString());
        stringBuilder = new StringBuilder();
    }
    else
    {
        stringBuilder.AppendLine(line);
    }

    line = await streamReader.ReadLineAsync();
}
```

**Comment by shocklateboy92** [comment]
That's more or less what I was thinking, except using the [EOF byte](https://en.wikipedia.org/wiki/End-of-Transmission_character) to signal the end of the file, instead of a string that can appear in a document like `ENDOFFILE`.

**Comment by belav** [comment]
> That's more or less what I was thinking, except using the EOF byte to signal the end of the file, instead of a string that can appear in a document like ENDOFFILE.

I knew there was something like this that existed, but I wasn't failing when googling EOF character and NULL character.

I did some digging into the performance of CSharpier against a single file.
One thing to note, passing `--fast` will speed up the formatting by bypassing the syntax tree validation. It cut ~10% off the time for formatting a single file.

By far the slowest part is roslyn initializing behind the scenes. It is ~40% of the time. That cost is only paid for the first file that is formatted.
Finding/initializing the IgnoreFile is ~8% of the time.
Finding/initializing the ConfigurationFile is ~3% of the time.
The library used to deal with command line parameters takes ~3% of the time.
Nothing else really stood out.

Even if we could optimize those last three, that doesn't seem like enough of a gain to make the sluggish feel go away. Keeping csharpier running to format files seems like the way to go.

**Comment by Ciantic** [comment]
I use this setup in VSCode:

1. Install [Trigger task on save -extension](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.triggertaskonsave)

Then add this task:

Workspace **tasks.json**:

```json5
{
    "version": "2.0.0",
    "tasks": [
        // Other tasks omitted
        {
            "label": "format (current file)",
            "type": "shell",
            "command": "dotnet csharpier ${relativeFile}",
        },
    ]
}
```

Workspace **settings.json**:

```json5
{
    "triggerTaskOnSave.restart": false,
    "triggerTaskOnSave.on": true,
    "triggerTaskOnSave.tasks": {
        "format (current file)": ["**/*.cs"]
    }

}
```

It kind of works.

**Comment by belav** [comment]
I made good progress today on modifying CSharpier to stay running and a VSCode extension that pipes files to the running instance. The formatting speed is 🚀 
![image](https://user-images.githubusercontent.com/3606529/142930401-8aec2cda-c14d-4d4c-aea8-fa9d24d150a7.png)

**Comment by belav** [comment]
The initial version of this is out https://marketplace.visualstudio.com/items?itemName=csharpier.csharpier-vscode

**Comment by Ciantic** [comment]
Great! I assume it doesn't yet leave it running in the background as it gives me ~600ms time for formatting single file:

```
["INFO" - 12.04.42] Formatting started for c:\Source\dotNET\PersistentJobs\src\PersistentJobs\PersistentJob.cs.
["INFO" - 12.04.42] Formatted in 643.4020001888275ms
```

**Comment by Ciantic** [comment]
Hmm, I updated the global tool to v0.12, it now works faster, but too fast for it's own sake, it cuts my file in half!

**Comment by belav** [comment]
> Great! I assume it doesn't yet leave it running in the background as it gives me ~600ms time for formatting single file:
It'll only leave it running if csharpier is >= 0.12.0. It was pretty easy to make the extension work with < 0.12.0 as well by just piping a single file.
