### ISSUE TITLE
Vertically Align Curly Braces

### ISSUE THREAD

**Issue by Kurt-von-Laven** [belav/csharpier#423]
This is just my opinion, so I am curious how others feel. CSharpier is already very nearly compatible with [ReSharper's CleanupCode](https://www.jetbrains.com/help/resharper/CleanupCode.html), and the two tools have the potential to complement each other nicely. The proposed change would both ensure that curly braces on separate lines are always vertically aligned (I think), and also bring CSharpier one step closer to being compatible with CleanupCode. CleanupCode offers [extremely fine-grained configurability options covering nearly every well-known curly brace style](https://www.jetbrains.com/help/resharper/EditorConfig_CSHARP_BracesPageSchema.html#Braces_layout), but not K & R curly braces only on lines containing only a close parenthesis.

Input:

```csharp
if (SomeReallyLongParentheticalExceedsThePrintWidthCausingCSharpierToWrapTheLine())
{
    ThisIfBlockContains();
    MoreThanOneLine();
}
```

Current Output:

```csharp
if (
    SomeReallyLongParentheticalExceedsThePrintWidthCausingCSharpierToWrapTheLine()
) {
    ThisIfBlockContains();
    MoreThanOneLine();
}
```

Desired Output:

```csharp
if (
    SomeReallyLongParentheticalExceedsThePrintWidthCausingCSharpierToWrapTheLine()
)
{
    ThisIfBlockContains();
    MoreThanOneLine();
}
```

**Comment by belav** [comment]
There was a little bit of discussion on this previously in #144, and #34. I refer to the current output as SpaceBrace, I don't know that it has an official name.
I mainly went with SpaceBrace to keep things consistent with how prettier formats js/ts and because at that point no one had really objected to it. As far as I can tell it came from the [airbnb styleguide](https://github.com/airbnb/javascript#control-statements)

One concern I have with trying to keep CSharpier compatible with other tools that format code is that it may be never-ending. How many other tweaks would need to be made to get CSharpier compatible with CleanupCode? I don't think this should be the only reason for making a change, but in this case I think there are other reasons to consider moving away from SpaceBrace.

If no other c# formatting tools support SpaceBrace, then it is probably not a common way to format c#. Is SpaceBrace going to turn off a lot of developers who aren't used to seeing it? SpaceBrace does save a line, but is it actually any better? I personally prefer it, but that might just be because I am used to it.

Does it make sense to try to keep csharpier somewhat consistent with prettier? My day job involves a mix of TypeScript and C#, so I like it being somewhat consistent. But there are other areas where they differ, the big one is that csharpier breaks before binary operators. 
I think that if there isn't an established standard for something in c#, and there is no strong argument for not doing it, then csharpier should strive to be consistent with prettier.

All of that being said, I am still torn on if csharpier should stick with SpaceBrace, switch to what you have suggested (BreakBreakBrace?), or go with this 3rd option (BreakBrace?) which is what I think I have seen most often in c# code.
```c#
if (
    SomeReallyLongParentheticalExceedsThePrintWidthCausingCSharpierToWrapTheLine())
{
    ThisIfBlockContains();
    MoreThanOneLine();
}

**Comment by Strepto** [comment]
Adding a data-point here for discussion. I have no merit to my opinion so feel free to disregard it! I'm using the terminology from the post above.

I can not remember seeing `space-brace` in C# code. As far as I know the `BreakBrace` is the most used, and the most common for Microsoft repos, as seen in [roslyn](https://github.com/dotnet/roslyn/blob/87bc72dbccbc80654cc3bf16113bb53fb80ef929/src/Features/Core/Portable/AddFileBanner/AbstractAddFileBannerCodeRefactoringProvider.cs#L38) and [runtime](https://github.com/dotnet/runtime/blob/f2ce707858cb225b4bd175986c6c91d1ae7aa33d/src/libraries/System.Text.Json/src/System/Text/Json/JsonHelpers.Date.cs#L238) (links are to arbitrarily picked examples). 

Prettier uses braces on the end of line (`if (true) {`) , so if keeping the `SpaceBrace` is more consistent in prettier I would consider using the same style for `if (true) {` in all c# statement blocks but that is an "all-in" approach which is not consistent with any common dotnet standard.

I think my personal "most readable formatting" idea leans towards `breakbreakbrace`, as the OP suggests.

**Comment by Kurt-von-Laven** [comment]
> One concern I have with trying to keep CSharpier compatible with other tools that format code is that it may be never-ending. How many other tweaks would need to be made to get CSharpier compatible with CleanupCode? I don't think this should be the only reason for making a change, but in this case I think there are other reasons to consider moving away from SpaceBrace.

Totally valid concern. I have only looked into this on one code base, so I can't say definitively, but I believe the literal answer to your question may be none whatsoever. CleanupCode offers a vast compendium of extremely fine-grained settings, and a few of them [like this one](https://www.jetbrains.com/help/resharper/EditorConfig_CSHARP_CSharpIndentStylePageSchema.html#resharper_csharp_align_multiline_binary_expressions_chain) would need to be changed from their default values.

My two cents would be that your best bet is to go with the flow in terms of what the community is doing in this case. My instinct is that would help keep the friction as low as possible for adopting this tool. Personally, I would prefer [any of the options provided by CleanupCode](https://www.jetbrains.com/help/resharper/EditorConfig_CSHARP_BracesPageSchema.html#Braces_layout), and beyond that have few opinions.

**Comment by Kurt-von-Laven** [comment]
This may already be on your radar, @belav, but I think this change implies a change to the README: https://github.com/belav/csharpier#after.

**Comment by belav** [comment]
> This may already be on your radar, @belav, but I think this change implies a change to the README: https://github.com/belav/csharpier#after.

It will need a change and I didn't have it on my checklist until now. Thanks!
