### ISSUE TITLE
Request: How to csharpier in combination with dotnet-format

### ISSUE THREAD

**Issue by Strepto** [belav/csharpier#436]
Hey, this tool looks great!

I would like to format my whitespace like `csharpier`, but also to use [`dotnet-format`](https://github.com/dotnet/format) to fix "linting". 

Is there a recommended approach to run both tools?

Thanks!

**Comment by belav** [comment]
I have not yet used dotnet-format and assumed it was concerned purely with formatting style, but it looks like there are a large number that are not formatting. See https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options?view=vs-2019

From my quick testing, there are definitely going to be formatting conflicts between csharpier and dotnet-format with how they wants to format whitespace. One possibility would be modifying the way csharpier formats whitespace so that it conforms with a set of dotnet-format rules. 

But! It looks like dotnet-format provides a way to run subsets of rules. The doc at https://github.com/dotnet/format#how-to-use appears to be outdated, but I believe this will run all of the non-whitespace rules. Running this against csharpier results in no changes. I believe because I don't have any rules defined in an editorconfig.
```bash
dotnet format --fix-style --fix-analyzers
```
 Assuming that accomplishes what you want, I can get the doc updated!

**Comment by Strepto** [comment]
I have not actually tested this combo myself yet. But I'll try to test your suggestion, and come back to you with results.

**Comment by Strepto** [comment]
The combination below seemingly works fine! Tested it on your repo, with some changes from dotnet but no formatting, and then apply your formatting in the end.

```ps1
dotnet-format --fix-style info --fix-analyzers info
```
```ps1
dotnet csharpier .
```

I think this can be a great combo, as dotnet-format is not opinionated enough about formatting. And csharpier has no linting. 

You could maybe consider promoting this combo here: https://github.com/dotnet/format/issues/246

**Comment by belav** [comment]
> The combination below seemingly works fine on dotnet-format 5!

Awesome! I have a PR for adding this info to the doc and I also included the changes from running the command. I will probably start using dotnet-format going forward.

> You could maybe consider promoting this combo here: dotnet/format#246

Someone else actually mentioned CSharpier on that issue already. I have been holding off on promoting too much until I consider CSharpier beta, and it is really close to that point now.

**Comment by Strepto** [comment]
Great :) 

Thanks for the feedback. Feel free to close this issue ✅
