### ISSUE TITLE
// csharpier-ignore

### ISSUE THREAD

**Issue by dlech** [belav/csharpier#581]
There are some cases where initializers have super-long lists of arguments. It would be helpful to have the equivalent of [// prettier-ignore](https://prettier.io/docs/en/ignore.html#javascript) to handle these cases.

**Comment by respel** [comment]
@dlech Can you list the scenarios you were having issues with? Maybe we can use that to improve csharpier itself.

One is tabular arrays and functions arguments that the prettier example gives.

**Comment by dlech** [comment]
Yes, arrays like this: https://github.com/dlech/SshAgentLib/blob/07c4d17f6648d13378dee274ebc8efa3c9b78144/SshAgentLib/Crypto/BCrypt.cs#L355

It makes for way too much scrolling when each item is on a new line.

**Comment by respel** [comment]
I like what google-java-format [does](https://github.com/google/google-java-format/issues/137#issuecomment-436319566). They have an exception for tabular arrays to keep the original formatting.

This is in line with the no-options philosophy but will be much more work.

**Comment by belav** [comment]
I think it makes sense to support `// csharpier-ignore` for edge cases like this. After noodling on it for the last day I think it may be pretty easy to implement if is is only supported at specific levels.
Meaning support it on members of classes, statements in methods, etc. 
But do not support in on arguments in invocations, the 8th invocation in a long chain, etc.
Playing around with prettier just now, I think prettier works that way.

I created #583 because even with support for ignoring lines, I think it may make sense to leave tabular initializers alone.

**Comment by belav** [comment]
0.15.0 is out now with the support for `// csharpier-ignore`
