### ISSUE TITLE
Rider - Support later versions

### ISSUE THREAD

**Issue by lsymds** [belav/csharpier#637]
Is there any reason why the Rider plugin doesn't support versions higher than 213? I tend to use EAP versions and I can't use this plugin with it as it has a maximum version defined.

Happy to guinea pig it and report back if that'd help.

**Comment by belav** [comment]
It looks like rider requires you to opt in to supporting new IDE versions. This is the first new version of rider that has come out since the csharpier plugin was created so I wasn't aware of that until now.

I tested the plugin with the EAP and submitted a new version to jetbrains, it takes them a couple days to approve things. I'll throw the version up here too so you don't need to wait for it.

**Comment by belav** [comment]
Here you go - https://github.com/belav/csharpier/releases/tag/rider-1.2.4

**Comment by lsymds** [comment]
This is great thank you. I can see JetBrains have already approved it and I'm using it now. Will report back any findings. Thank you again for CSharpier, it's fantastic and becoming a key part of my workflow.
