### ISSUE TITLE
Visual Studio 2022: The system cannot find the file specified

### ISSUE THREAD

**Issue by tbrixen** [belav/csharpier#639]
I'm getting the following error from the Output tab in Visual Studio 2022 with the CSharpier extension version 1.2.2 (and CSharpier version 0.16.0)

```
Starting
Ensure there is a csharpier process for C:\Users\tbr\source\repos\dotnetnewwebnohttps
Looking for C:\Users\tbr\source\repos\dotnetnewwebnohttps\.config/dotnet-tools.json
Found version 0.16.0 in C:\Users\tbr\source\repos\dotnetnewwebnohttps\.config/dotnet-tools.json
Directory at C:\Users\tbr\AppData\Local\CSharpier\0.16.0 already exists
Adding new version 0.16.0 process for C:\Users\tbr\source\repos\dotnetnewwebnohttps
Exception: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at CSharpier.VisualStudio.CSharpierProcessPipeMultipleFiles..ctor(String csharpierPath, Logger logger)
   at CSharpier.VisualStudio.CSharpierProcessProvider.SetupCSharpierProcess(String directory, String version)
```

The project is a .NET 6 webapp (created using `dotnet new webapp`).

I installed the CSharpier locally to the project using instructions from https://csharpier.com/docs/Installation

```
dotnet new tool-manifest
dotnet tool install csharpier
```

I installed Visual Studio 2022 extension from https://marketplace.visualstudio.com/items?itemName=csharpier.CSharpier

When I saw the error, I installed the cli globally also uinsg `dotnet tool install -g csharpier`.

The commandline tool `dotnet tool run dotnet-csharpier .` works as intended.

I have enabled "Log Debug Messages". Is it logged to the Output tab in Visual Studio?

What else can I try? Can I see more log output somewhere else?

**Comment by belav** [comment]
Some of the messages that you are seeing are debug messages, they are logged to the same output window.

Because the plugin keeps csharpier running in the background, it installs it to a custom path. My guess is that csharpier was not successfully installed to that path - `C:\Users\tbr\AppData\Local\CSharpier\0.16.0`. You should see the dotnet-csharpier.exe file in that folder.

Some steps to try

1. Close visual studio
2. Delete `C:\Users\tbr\AppData\Local\CSharpier\0.16.0`
3. Reopen the solution to see if it is resolved.
4. If still not working
5. Close visual studio
6. Run `dotnet tool install csharpier --version 0.16.0 --tool-path "C:\Users\tbr\AppData\Local\CSharpier\0.16.0"`
7. Reopen the solution to see if it is resolved.

I can look into adding code so that the plugin can detect this condition and recover from it if possible.

**Comment by tbrixen** [comment]
Your guess seemed to be correct. After deleting the `0.16.0` folder and re-opening Visual Studio the extension worked! Thank you.

If interested, the `0.16.0` folder did not contain `dotnet-csharpier.exe`. It only had a folder named `.store` which contained an empty folder called `.state`.
