### ISSUE TITLE
Option for indentation 

### ISSUE THREAD

**Issue by jods4** [belav/csharpier#645]
First, thanks for this project! 
I'm a big fan of Prettier and really happy to see a similar formatting tool for C#.

I understand the opiniated Prettier philosophy of keeping options to a strict minimum that is now frozen, but I feel like indent style (tabs vs spaces) and width are amongst the few things that should be configurable. 
They are (unreasonably) very polarizing and forcing spaces might hinder adoption of Csharpier.

I'm sure you're aware that Prettier does let you configure them:
https://prettier.io/docs/en/options.html#tab-width
Also observe the default Prettier tab-width is `2`, csharpier uses `4`.

The best part is that it seems you already have full support for those option, they just need to be exposed?
https://github.com/belav/csharpier/blob/master/Src/CSharpier.Cli/ConfigurationFileOptions.cs#L44-L48

**Comment by belav** [comment]
Those options were hidden early on with the thought that maybe everybody had settled on using 4 spaces for indentation. I always assumed that eventually someone was going to request that it gets added so left the code around so it would be easy to re-add the options.

I'll get the options back in for the next release!

**Comment by jods4** [comment]
> that maybe everybody had settled on using 4 spaces for indentation

😁 You don't read twitter enough! 
Seems this debate is heated as ever, although I don't really get it myself.

Personally I like 2-spaces, prettier style.
I've read that in teams where some devs have vision disabilities, using tabs is really important.

**Comment by belav** [comment]
> I've read that in teams where some devs have vision disabilities, using tabs is really important.

I read an article that made a really good case for that. Someone worked on a team where they needed both extremes, the tabs being about the size of one space and the size of eight spaces.

It would also mean that people with a preference for two spaces don't have to fight with people that prefer four spaces. My other complaint about tabs was how large github displays them, but I just discovered you can use customize them in your account page or using a query string.

CSharpier followed prettier in using two space aligns in some cases (even when indent is set to 4 spaces or tabs) which would probably cause issues for someone who is using tabs because vision disabilities. I think that is a good argument for #617.
