### ISSUE TITLE
VS Code plugin not formatting file

### ISSUE THREAD

**Issue by wakemaster39** [belav/csharpier#715]
I am currently running:

Visual Studio Code: Version: 1.70.1
CSharpier - Code Formatter: 1.3.0
MacOS 12.5 on a M1 Macbook Pro

This is my global settings.json:
```json
{
    "[csharp]": {
        "editor.defaultFormatter": "csharpier.csharpier-vscode"
    }
}
```

The test repo I have can be found here: https://github.com/wakemaster39/csharpier-debug

Inside of the Class1.cs, I am attempting to run `Format Document`, `Format Document With...` and also tried format document on autosave.

What I am expecting to occur is that the file should be formatted.

What is occurring is that all Actions lead to a result of a blue "working" bar along the top of the editor while no action is being 
taken.

![Screen Shot 2022-08-15 at 3 55 04 PM](https://user-images.githubusercontent.com/694131/184710274-2f9f382f-2921-4177-94b1-791d151c1dac.png)

When I leave the file and return to the file, the bar is gone but no changes have been made.

Enabling the debug logs, here is the output I am getting:

```bash
["INFO" - 4:02:48 PM] Initializing csharpier-vscode
["INFO" - 4:02:52 PM] Formatting started for /Users/cameronhurst/personal/csharper-debug/src/Test.Domain/Class1.cs.
["DEBUG" - 4:02:52 PM] Ensure there is a csharpier process for /Users/cameronhurst/personal/csharper-debug/src/Test.Domain
["DEBUG" - 4:02:52 PM] Looking for /Users/cameronhurst/personal/csharper-debug/src/Test.Domain/*.csproj
["DEBUG" - 4:02:52 PM] Looking at /Users/cameronhurst/personal/csharper-debug/src/Test.Domain/Test.Domain.csproj
["DEBUG" - 4:02:52 PM] Looking for /Users/cameronhurst/personal/csharper-debug/src/Test.Domain/.config/dotnet-tools.json
["DEBUG" - 4:02:52 PM] Looking for /Users/cameronhurst/personal/csharper-debug/src/*.csproj
["DEBUG" - 4:02:52 PM] Looking for /Users/cameronhurst/personal/csharper-debug/src/.config/dotnet-tools.json
["DEBUG" - 4:02:52 PM] Looking for /Users/cameronhurst/personal/csharper-debug/*.csproj
["DEBUG" - 4:02:52 PM] Looking for /Users/cameronhurst/personal/csharper-debug/.config/dotnet-tools.json
["DEBUG" - 4:02:52 PM] Found version 0.19.0 in /Users/cameronhurst/personal/csharper-debug/.config/dotnet-tools.json
["DEBUG" - 4:02:52 PM] File at /Users/cameronhurst/.cache/csharpier/0.19.0 already exists
["DEBUG" - 4:02:52 PM] Adding new version 0.19.0 process for /Users/cameronhurst/personal/csharper-debug/src/Test.Domain
["DEBUG" - 4:02:52 PM] Warm CSharpier with initial format
["DEBUG" - 4:07:07 PM] Ensure there is a csharpier process for /Users/cameronhurst/personal/csharper-debug/src/Test.Domain
["INFO" - 4:07:13 PM] Formatting started for /Users/cameronhurst/personal/csharper-debug/src/Test.Domain/Class1.cs.
```

I notice it is difference from a large amount of other logs listed in errors in that it does not appear to get to the actual formatting part, it just seems to hang. 

I have attempted to uninstall and reinstall the plugin, attempted on multiple projects but I am experiencing the same result. csharpier executed from the command line works fine. 

I am happy to provide any other details or take additional steps to help replicate the issue.

**Comment by belav** [comment]
Thanks for all the details.

My guess based on the logs is that the vscode plugin is failing to pipe input to the csharpier process that it keeps running. Or the csharpier process being used to format files is hanging somehow. After the `Warm CSharpier with initial format` and the `Formatting started...` logs there should be at least one `Got chunk of size x` log. Based on #610 the csharpier process should work with piping files on an M1 mac.

Locally I have debug logging in csharpier which helps with troubleshooting piping problems, and I could expose that as option. That would tell us if the problem is in the vscode plugin or csharpier. I can try to get that done in the next couple of days.

Another option if you are feeling more adventurous would be for you to get the vscode plugin running and debug into this file - https://github.com/belav/csharpier/blob/master/Src/CSharpier.VSCode/src/CSharpierProcessPipeMultipleFiles.ts
And if the problem isn't there then it is on the csharpier side. This file does the debug logging and has hardcoded windows paths in it that would need to change - https://github.com/belav/csharpier/blob/master/Src/CSharpier/DebugLogger.cs
Dropping a locally built csharpier over /Users/cameronhurst/.cache/csharpier/0.19.0 or modifying the vscode plugin to use csharpier from your bin would hopefully get you some debug output from csharpier.

**Comment by wakemaster39** [comment]
This was my first time debugging a VS Code extension so I am not entirely sure I did it right. I opened only the extensions project installed the dependencies and pressed `F5` on the Extension.ts file like I found in a blog post. The debugging experience was weird, it felt like it was jumping over lines and not really respecting step over properly. Not sure if this just me not understanding it correctly.

Either way, here is the output I get from debugging:

```bash
Initializing csharpier-vscode
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89
Formatting started for /Users/cameronhurst/personal/csharper-debug/src/Test.Domain/Class1.cs.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89
Ensure there is a csharpier process for /Users/cameronhurst/personal/csharper-debug/src/Test.Domain
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89
Looking for /Users/cameronhurst/personal/csharper-debug/src/Test.Domain/*.csproj
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89
Looking at /Users/cameronhurst/personal/csharper-debug/src/Test.Domain/Test.Domain.csproj
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89
Looking for /Users/cameronhurst/personal/csharper-debug/src/Test.Domain/.config/dotnet-tools.json
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89
Looking for /Users/cameronhurst/personal/csharper-debug/src/*.csproj
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89
Looking for /Users/cameronhurst/personal/csharper-debug/src/.config/dotnet-tools.json
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89
Looking for /Users/cameronhurst/personal/csharper-debug/*.csproj
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89
Looking for /Users/cameronhurst/personal/csharper-debug/.config/dotnet-tools.json
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89
Found version 0.19.0 in /Users/cameronhurst/personal/csharper-debug/.config/dotnet-tools.json
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89
File at /Users/cameronhurst/.cache/csharpier/0.19.0 already exists
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89
Adding new version 0.19.0 process for /Users/cameronhurst/personal/csharper-debug/src/Test.Domain
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89
Warm CSharpier with initial format
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89
Error: Unexpected SIGPIPE
	at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap.js:1:407)
	at process.emit (/Users/cameronhurst/personal/csharpier/Src/CSharpier.VSCode/lib/events.js:390:28)
	at Signal.callbackTrampoline (node:internal/async_hooks:130:17) {stack: 'Error: Unexpected SIGPIPE
	at process.<anonym…Trampoline (node:internal/async_hooks:130:17)', message: 'Unexpected SIGPIPE'}
```

I noticed that the process (I'm assuming crashes) when it tries to process my file. But it seems to handle the warming part just fine. I also noticed that even during the warming process, there is no call to the `stdout` hook. I am not sure if this is expected or not.

**Comment by belav** [comment]
Its been a while since I debugged the vscode extension, it may be that it jumps around because of a source map issue between the js that is actually running and the ts in the project.

I haven't seen anything like this before and my googling was failing, but I just ran across this - https://github.com/microsoft/vscode-go/issues/1845
It sounds like this error happens if you try to pipe content to a badly spawned process.

Does it look like csharpier is in the directory at `/Users/cameronhurst/.cache/csharpier/0.19.0` ? I have an open issue where sometimes csharpier fails to install to the custom directory, and the extension can't recover from the problem. I am wondering if this is the same issue, but the error looks different because it's on an m1.

You can install csharpier to that directory yourself, or delete it and see if the extension installs it correctly. The command to install to the custom location is
```
dotnet tool install csharpier --version 0.19.0 --tool-path [thePath]

**Comment by Meligy** [comment]
Probably also worth trying this setting as well:

```json
"editor.formatOnSaveMode": "file",
```

I think I read someone in the docs that selection formatting does't work. It might be affecting the "changes" save mode as well.

**Comment by wakemaster39** [comment]
I attempted the change listed and still have the same output with no chunk size handling getting outputted.

I'll give this a shot on a Linux box I have later on to make sure its completely isolated to my M1.

**Comment by belav** [comment]
I have changes to the VSCode extension that attempt to recover from a bad install of csharpier. But if you did the steps manually and it didn't fix it, then I don't believe that will help.

**Comment by wakemaster39** [comment]
Honestly not sure why, but the changes you pushed did fix my issue!

Thanks for the help, not sure why but I'll take the W.

**Comment by belav** [comment]
@RReverser if you are still having problem could you open a new issue and include any csharpier logs. If I remember correctly (I don't use VSCode normally) there is an output window that you can select CSharpier on.
`csharpier.enableDebugLogs` is an option that will provide more information.

**Comment by RReverser** [comment]
Yeah I found this issue and commented because logs were identical (also hanging right after "Formatting started..." and just not doing anything).

I'll check again tomorrow and create a new issue if nothing changed.
