### ISSUE TITLE
Tuple formatting

### ISSUE THREAD

**Issue by BenjaBobs** [belav/csharpier#735]
Tuples are not always formatted in a way that is clearly readable.

Example of tuple as return value
```cs
public async Task<(
    ILookup<string, int> someLookup,
    ILookup<int, string> reverseLookup,
    ILookup<string, ClassName> thirdLookup
)> CreateLookups()
{
  return (null, null);
}
```

is formatted as
```cs
public async Task<(ILookup<string, int> someLookup, ILookup<int, string> reverseLookup, ILookup<
        string,
        ClassName
    > thirdLookup)> CreateLookups()
{
    return (null, null);
}
```

Example of tuple as input
```cs
public void TuplesAsInput(
    (
        int myInt,
        string myString,
        ClassName myClassNameInstance,
        Dictionary<int, string> wordList
    ) inputArgs
 )
 {
   // do something
 }
```

is formatted as
```cs
public void TuplesAsInput(
    (int myInt, string myString, ClassName myClassNameInstance, Dictionary<
        int,
        string
    > wordList) inputArgs
)
{
    // do something
}
```

Thanks for creating this great software 🚀

**Comment by belav** [comment]
Thanks for the report. This seems similar other issues I have seen with generics where they break when they would look better grouped and the parent breaking instead.

**Comment by monkey0506** [comment]
Hi. I'm not very familiar with this project, but I tried out your extension and ended up here. I am writing some utility classes using generics that accept up to 16 generic arguments plus a generic return type, so there's up to 17 generic arguments, and as many variations on what would otherwise be the same class. I partially automated generating this code file that is now just under 4k lines and I was looking to simplify formatting it. Unfortunately your extension places every generic parameter on its own line in the file, including in the interface lists (each class implements the relevant `IEquatable` and `IEqualityOperators` interfaces), resulting in a file of over 10k lines, **most** of which are nothing more than `T1,`, `T2,`, etc. Are there any plans to allow customizing/configuring how formatting is handled? I've read good reviews of your extension, but my particular use case isn't a good fit for the current version. Thanks!

**Comment by BenjaBobs** [comment]
You can configure file ignoring if it's just the one file.

**Comment by belav** [comment]
@monkey0506 Do you have an example of one of the methods and how you'd prefer to see it? Maybe if all the arguments are just a few characters csharpier should leave them on a single line. Otherwise as BenjaBobs mentioned you can ignore whole files, or also parts of files. See https://csharpier.com/docs/Ignore for more info.
