### ISSUE TITLE
CSharpier needs to be installed globally to format files...

### ISSUE THREAD

**Issue by paweston70** [belav/csharpier#745]
Related to https://github.com/belav/csharpier/issues/574

I'm getting the same issue with version vscode-1.3.5\build.

This tends to display when I switch between tabs from something that isn't C# to something that is.
![demo0](https://user-images.githubusercontent.com/37217207/197543375-097cc3f0-031c-4329-8cdc-93f44c4286c6.png)

About dialog...
![demo1](https://user-images.githubusercontent.com/37217207/197543343-07b97377-ddaa-4731-96b3-ce5785e12ada.png)

I don't have the facility to record a video, unfortunately.

**Comment by snebjorn** [comment]
It doesn't **need** to be globally installed. I have it locally installed and that seems to work.

```
dotnet new tool-manifest
dotnet tool install csharpier
```

But it would be neat if it was bundled with the VSCode extension - if possible

**Comment by WestieNHS** [comment]
> It doesn't **need** to be globally installed. I have it locally installed and that seems to work.
> 
> ```
> dotnet new tool-manifest
> dotnet tool install csharpier
> ```
> 
> But it would be neat if it was bundled with the VSCode extension - if possible

As stated, this message pops up for me on every install. I simply don't have time to root out every single problem with every single plugin I install. If this fails for me, then it fails for others too.

**Comment by snebjorn** [comment]
it was merely a suggestion to people that didn't know or want to install CSharpier globally

**Comment by belav** [comment]
When the extension runs into a file outside of what it considers to be the project, it pops up the "install globally message" if csharpier isn't install globally.

With rider if you browse to the source of a nuget package class it will decompile the code to a temp location. That temp location was outside of the project, so this message was appearing in rider on occasion. I modified the rider extension to not display the message on those types of files. I use rider daily so I was able to track down all of the cases where that occurred.

This may be the same sort of issue in VSCode but I haven't had a chance to try to reproduce it yet. If it is a file that is part of your project, then maybe a proper fix is needed instead of just hiding the warning.

**Comment by belav** [comment]
The message you are seeing is referring to the directory the extension itself is installed in `C:\Users\bela\.vscode\extensions\csharpier.csharpier-vscode-1.3.6\build`

The only files in there are javascript files, at least for me locally. Digging through the code, I can't see any reason that it should ever think that a csharp file is in that directory.

Are you still able to reproduce the problem? And if so, are their any debug logs about `Unsaved document has no directory, falling back to...` prior to it? The only thing I can come up with is that the extension directory is being used as the context for unsaved documents, but I haven't been able to get that to happen locally.

**Comment by WestieNHS** [comment]
> The message you are seeing is referring to the directory the extension itself is installed in `C:\Users\bela\.vscode\extensions\csharpier.csharpier-vscode-1.3.6\build`
> 
> The only files in there are javascript files, at least for me locally. Digging through the code, I can't see any reason that it should ever think that a csharp file is in that directory.
> 
> Are you still able to reproduce the problem? And if so, are their any debug logs about `Unsaved document has no directory, falling back to...` prior to it? The only thing I can come up with is that the extension directory is being used as the context for unsaved documents, but I haven't been able to get that to happen locally.

Morning belav,

Apologies for the delay in getting back to you.

I've tested C# again with your plugin, but am not getting any issues now. I've tested with a project (opening a set of folders) and moving between the files, and with individual files on an adhoc basis, and the issue seems to have gone.

One thing I did note previously with this issue, was that the console would open as soon as I opened a C# file. This no longer happens, either.

I have upgraded VS Code a couple of times since October, so this may also have something to do with it if you have not modified your code.

I do love this extension, by the way - it's so useful. Thank-you for all of your hard work.

Paul.

**Comment by belav** [comment]
You're welcome! And I'm glad that things are working for you now. I'm going to close out this issue.
