### ISSUE TITLE
CSharpier fails on foreign characters in code

### ISSUE THREAD

**Issue by Svish** [belav/csharpier#833]
Tried out CSharpier for the first time now, on a Norwegian code-base. A few files contains Norwegian letters, like `æ`, `ø`, `å`, and they seem to generate errors like these when I run `dotnet csharpier .` in the project:
```
Error ./src/The.Project/Features/Common/Enums/Terminstatus.cs - Failed to compile so was not formatted.
  (10,14): error CS1056: Unexpected character 'ï¿½'
  (10,15): error CS1003: Syntax error, ',' expected
```
Below is the file it complains about, and `(10,14)` is indeed the Norwegian letter `å`.
```cs
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace The.Project.Features.Common.Enums
{
    [JsonConverter(converterType: typeof(StringEnumConverter))]
    public enum Terminstatus
    {
        Betalt,
        Utestående
    }
}
```
Not sure what the `Syntax error, ',' expected` is about, but that's a consistent error too. All the `Unexpected character ...` errors, are immediately followed by one of those, but the character it expects varies depending on the context. In the example above, it expects a `,`, but in a `switch` (e.g. `case Terminstatus.Utestående:`) the expected character is `:`.

The project/code builds and works fine in Visual Studio, so the characters are valid where they are.

```ps
PM> dotnet csharpier --version
0.22.1
```

**Comment by belav** [comment]
CSharpier only supports UTF8 and UTF8-BOM files, I'm guessing your files are saved with a different encoding. That would result in the å being read in as something else, possibly with a space in it. Or some other character that isn't allowed in the name of an enum.

Initially I attempted to have CSharpier support any type of file encoding, but I've been unable to find a way to reliably detect file encodings. There were some edge cases where UTF8 files were detected incorrectly and read improperly. That resulted in code that couldn't compile much like what you are seeing.

As for how to switch files to UTF8 - I don't know if I have a recommended approach because I haven't had to do it yet. It sounds like there are a few options - dotnet-format + an editorconfig, powershell or other scripting, various free utilities.

**Comment by Svish** [comment]
Aah, that makes sense. I'm so used to our frontend-files being UTF-8, so didn't really think about our backend-stuff not being UTF-8, but that may very well be the case, yes.

I will check and see if that's the case, and look into converting the format.

**Comment by Svish** [comment]
Confirmed! It was the encoding that was an issue.

Was able to fix it quite easily by adding `charset = utf-8-bom` to an `.editorconfig`, and then running `dotnet format .`. This seems to have converted all `*.cs` files to that charset, and running `dotnet csharpier .` now no longer gives any warnings 😊👍
