### ISSUE TITLE
Format on save not working on VS 17.7.3

### ISSUE THREAD

**Issue by lpatvezina** [belav/csharpier#949]
I updated my VS 2022 Community to version 17.7.3 yesterday and the format on save doesn't to work since then.

I always have to use the Reformat with CSharpier option in the right click context menu action.

I'm using version 1.4.3 of the extension

**Comment by belav** [comment]
I have an open report with VS because I believe the problem is with VS itself and not the csharpier plugin. This comment has a link to it https://github.com/belav/csharpier/issues/790#issuecomment-1694494603. That issue also discusses a couple potential workarounds that may help until I hear back from microsoft.

**Comment by lpatvezina** [comment]
Ok, thanks for the comment.  I'll close this ticket since it is a duplicate.
